const games = [
  
  //SPIL : JEG HAR ALDRIG
  {
    id: "never_have_i_ever",
    title: "Jeg har aldrig",
    headerTitle: "Jeg har\nALDRIG",

    cardsPerRound: null,
    mode: "normal",

    description:
      "Jeg har aldrig er et sjovt festspil, der afslører pinlige historier, vilde oplevelser og overraskende hemmeligheder om dig og dine venner.",

    rules: [
      "Én deltager trækker et kort og læser et “Jeg har aldrig...”-udsagn højt.",
      "Alle starter med 5 liv/fingre i vejret.",
      "Har du gjort det, der står på kortet, tager du én finger ned.",
      "Den første spiller, der har alle 5 fingre nede, skal tage 5 tår og runden er slut.",
    ],

    cards: [
        "Jeg har aldrig ghostet nogen.",
        "Jeg har aldrig selv været blevet ghostet.",
        "Jeg har aldrig stalket en eks på sociale medier.",
        "Jeg har aldrig oprettet en fake profil for at kigge på nogen.",
        "Jeg har aldrig været forelsket i min bedste vens kæreste.",
        "Jeg har aldrig kysset en person, jeg lige havde mødt.",
        "Jeg har aldrig fortrudt et kys dagen efter.",
        "Jeg har aldrig haft to personer interesseret i mig på samme tid.",
        "Jeg har aldrig været på mere end én date på samme uge.",
        "Jeg har aldrig matchet med nogen på en datingside, som jeg kendte i forvejen.",
        "Jeg har aldrig været på en blind date.",
        "Jeg har aldrig løjet om min alder.",
        "Jeg har aldrig løjet om min højde.",
        "Jeg har aldrig løjet om mit job for at imponere nogen.",
        "Jeg har aldrig været forelsket i en lærer eller underviser.",
        "Jeg har aldrig haft et crush på en ven eller veninde.",
        "Jeg har aldrig kysset min bedste ven.",
        "Jeg har aldrig skrevet til en eks, mens jeg var fuld.",
        "Jeg har aldrig fået et 'U up?'-opkald eller en besked sent om natten.",
        "Jeg har aldrig været tilbage til en eks, selvom jeg vidste, det var en dårlig idé.",
        "Jeg har aldrig haft sex i en bil.",
        "Jeg har aldrig haft sex på stranden.",
        "Jeg har aldrig haft sex i et sommerhus.",
        "Jeg har aldrig haft sex i et telt.",
        "Jeg har aldrig haft sex, mens andre sov i samme rum.",
        "Jeg har aldrig haft sex i et svømmebassin.",
        "Jeg har aldrig kysset nogen i regnvejr.",
        "Jeg har aldrig prøvet at være alt for stille for ikke at blive opdaget.",
        "Jeg har aldrig haft et sugemærke, jeg måtte skjule.",
        "Jeg har aldrig haft sex om morgenen.",
        "Jeg har aldrig haft sex på en ferie.",
        "Jeg har aldrig kysset nogen til en festival.",
        "Jeg har aldrig flirtet med en dørmand.",
        "Jeg har aldrig haft en flirt med en bartender.",
        "Jeg har aldrig været sammen med nogen, jeg mødte samme aften.",
        "Jeg har aldrig kysset en fremmed i byen.",
        "Jeg har aldrig haft en sexvideo-opkald eller sexvideochat.",
        "Jeg har aldrig haft sex efter en bytur.",
        "Jeg har aldrig haft et booty call.",
        "Jeg har aldrig været forelsket i en flirt.",
        "Jeg har aldrig drukket shots, jeg ikke kunne huske navnet på.",
        "Jeg har aldrig mistet min pung på en bytur.",
        "Jeg har aldrig mistet min telefon på en bytur.",
        "Jeg har aldrig taget en taxa hjem alene.",
        "Jeg har aldrig vågnet op med tømmermænd uden at vide hvorfor.",
        "Jeg har aldrig danset på en bar.",
        "Jeg har aldrig danset på et bord.",
        "Jeg har aldrig sunget karaoke foran fremmede.",
        "Jeg har aldrig bestilt natmad for over 300 kr.",
        "Jeg har aldrig været den sidste, der gik hjem fra en fest.",
        "Jeg har aldrig sovet på en sofa efter en fest.",
        "Jeg har aldrig sendt en talebesked, jeg fortrød.",
        "Jeg har aldrig ringet til nogen, mens jeg var fuld.",
        "Jeg har aldrig skrevet 'jeg elsker dig', mens jeg var fuld.",
        "Jeg har aldrig glemt min jakke i byen.",
        "Jeg har aldrig haft to forskellige sko på efter en bytur.",
        "Jeg har aldrig været på en pubcrawl.",
        "Jeg har aldrig været så fuld, at mine venner måtte passe på mig.",
        "Jeg har aldrig været så fuld, at jeg faldt i søvn med alt tøjet på.",
        "Jeg har aldrig sagt 'én drink mere', selvom jeg godt vidste, det var en dårlig idé.",
        "Jeg har aldrig sendt en sexvideo-emoji til den forkerte.",
        "Jeg har aldrig sagt 'mor' eller 'far' til en lærer eller chef.",
        "Jeg har aldrig gået ind i en glasdør.",
        "Jeg har aldrig vinket til den forkerte.",
        "Jeg har aldrig faldet foran en person, jeg ville imponere.",
        "Jeg har aldrig grinet på et upassende tidspunkt.",
        "Jeg har aldrig haft toiletpapir siddende under skoen.",
        "Jeg har aldrig opdaget alt for sent, at mine bukser var gået op.",
        "Jeg har aldrig haft noget mellem tænderne en hel aften.",
        "Jeg har aldrig snorket så højt, at andre kommenterede det.",
        "Jeg har aldrig sendt en besked og straks fortrudt den.",
        "Jeg har aldrig glemt navnet på en person, jeg var på date med.",
        "Jeg har aldrig lavet en pinlig telefonsamtale på højttaler uden at vide det.",
        "Jeg har aldrig stalket en ny kærestes eks.",
        "Jeg har aldrig slettet et opslag, fordi det fik for få likes.",
        "Jeg har aldrig taget over 20 billeder for at få ét godt.",
        "Jeg har aldrig redigeret et billede mere, end jeg burde.",
        "Jeg har aldrig kigget på en persons profil flere år tilbage.",
        "Jeg har aldrig sendt en besked og derefter sat telefonen på flytilstand.",
        "Jeg har aldrig fortrudt noget, jeg lagde op.",
        "Jeg har aldrig lavet en fake undskyldning for ikke at svare.",
        "Jeg har aldrig været online uden at svare med vilje.",
        "Jeg har aldrig set en persons story igen og igen.",
        "Jeg har aldrig løjet om, hvor mange personer jeg har været sammen med.",
        "Jeg har aldrig overdrevet en historie for at gøre den mere spændende.",
        "Jeg har aldrig været forelsket i to personer på samme tid.",
        "Jeg har aldrig været den anden person i en kærlighedstrekant.",
        "Jeg har aldrig været på date kun for den gratis mad.",
        "Jeg har aldrig flirtet mig ud af en bøde eller en regning.",
        "Jeg har aldrig haft en hemmelig flirt, som ingen kendte til.",
        "Jeg har aldrig haft et crush på en venindes eller vens søskende.",
        "Jeg har aldrig kysset nogen for at gøre en anden jaloux.",
        "Jeg har aldrig været tiltrukket af en person, jeg først ikke kunne lide.",
        "Jeg har aldrig været forelsket ved første blik.",
        "Jeg har aldrig tænkt 'det her bliver en dårlig idé' og gjort det alligevel.",
        "Jeg har aldrig holdt noget skjult for en partner.",
        "Jeg har aldrig været sammen med nogen, selvom jeg vidste, det ville skabe drama.",
        "Jeg har aldrig fortrudt en beslutning allerede morgenen efter.",
        "Jeg har aldrig fået følelser for en person, jeg kun skulle have haft det sjovt med.",
        "Jeg har aldrig kysset nogen, selvom jeg vidste, det var en dårlig idé.",
        "Jeg har aldrig haft et crush på en venindes eller vens eks.",
        "Jeg har aldrig været forelsket i en person, der boede alt for langt væk.",
        "Jeg har aldrig flirtet med nogen, jeg egentlig ikke var interesseret i.",
        "Jeg har aldrig været på en date kun for at se, hvad der skete.",
        "Jeg har aldrig fortrudt at have skrevet først.",
        "Jeg har aldrig ventet med vilje på at svare en besked.",
        "Jeg har aldrig ladet som om, jeg ikke havde set en besked.",
        "Jeg har aldrig tjekket, hvornår nogen sidst var online.",
        "Jeg har aldrig slettet en besked, inden den blev læst.",
        "Jeg har aldrig taget et screenshot af en datingside.",
        "Jeg har aldrig været nervøs før et første kys.",
        "Jeg har aldrig haft et crush på en person, jeg kun kendte gennem sociale medier.",
        "Jeg har aldrig været forelsket i en person, der ikke vidste, jeg eksisterede.",
        "Jeg har aldrig kysset nogen i et spil.",
        "Jeg har aldrig været på en date, hvor der var total akavet stilhed.",
        "Jeg har aldrig ønsket, at en date sluttede hurtigere.",
        "Jeg har aldrig givet et falsk kompliment.",
        "Jeg har aldrig været jaloux på en eks' nye kæreste.",
        "Jeg har aldrig haft en flirt med en nabo.",
        "Jeg har aldrig haft et crush på en person over 10 år ældre end mig.",
        "Jeg har aldrig haft et crush på en person over 10 år yngre end mig.",
        "Jeg har aldrig flirtet med en person, selvom jeg vidste, vi aldrig skulle ses igen.",
        "Jeg har aldrig givet mit nummer til en fremmed.",
        "Jeg har aldrig fået et telefonnummer på en serviet.",
        "Jeg har aldrig kysset nogen nytårsaften.",
        "Jeg har aldrig sendt en besked, som jeg straks slettede igen.",
        "Jeg har aldrig haft sommerfugle i maven over en besked.",
        "Jeg har aldrig været mere interesseret i en persons ven end personen selv.",
        "Jeg har aldrig haft en flirt på arbejdet.",
        "Jeg har aldrig haft en flirt på studiet.",
        "Jeg har aldrig haft en flirt i fitnesscenteret.",
        "Jeg har aldrig flirtet med en tjener.",
        "Jeg har aldrig været på date med en, jeg mødte online.",
        "Jeg har aldrig været på en dobbeltdate.",
        "Jeg har aldrig været til et bryllup og fået et crush.",
        "Jeg har aldrig haft et crush på en roomie.",
        "Jeg har aldrig haft en flirt, der kun varede én aften.",
        "Jeg har aldrig fået et kompliment, jeg stadig kan huske.",
        "Jeg har aldrig været nervøs for at møde nogens forældre.",
        "Jeg har aldrig været nervøs for at præsentere en kæreste for mine venner.",
        "Jeg har aldrig haft en eks, jeg stadig tænker på.",
        "Jeg har aldrig været tilbage hos en eks for at hente ting, der egentlig ikke var vigtige.",
        "Jeg har aldrig kysset en person, jeg først ikke syntes var attraktiv.",
        "Jeg har aldrig haft et crush på en kendis.",
        "Jeg har aldrig fantaseret om en kendt person.",
        "Jeg har aldrig sendt et billede bare fordi jeg syntes, jeg så godt ud.",
        "Jeg har aldrig brugt mere end en time på at gøre mig klar til en date.",
        "Jeg har aldrig taget en omvej for at møde en person, jeg havde et crush på.",
        "Jeg har aldrig været på en date, hvor regningen blev akavet.",
        "Jeg har aldrig flirtet med en person, mens en anden flirtede med mig.",
        "Jeg har aldrig været på en fest kun for at se én bestemt person.",
        "Jeg har aldrig kysset nogen under mistelten.",
        "Jeg har aldrig været den, der tog det første skridt.",
        "Jeg har aldrig været for genert til at tage det første skridt.",
        "Jeg har aldrig håbet på, at en person ville skrive først.",
        "Jeg har aldrig læst en besked igen og igen for at overanalysere den.",
        "Jeg har aldrig spurgt mine venner om hjælp til at svare på en besked.",
        "Jeg har aldrig sendt en besked og fortrudt den med det samme.",
        "Jeg har aldrig været i tvivl om, hvorvidt en date faktisk var en date.",
        "Jeg har aldrig haft en samtale, der blev meget mere flirtende, end jeg havde regnet med.",
        "Jeg har aldrig haft en flirt, der startede på en ferie.",
        "Jeg har aldrig danset tæt med en fremmed.",
        "Jeg har aldrig kysset nogen på dansegulvet.",
        "Jeg har aldrig haft et crush på en person, bare på grund af deres stemme.",
        "Jeg har aldrig været forelsket i en person, jeg mødte på ferie.",
        "Jeg har aldrig haft en flirt, der endte i et venskab.",
        "Jeg har aldrig mødt en person igen, selvom første date var forfærdelig.",
        "Jeg har aldrig taget hjem tidligere fra en fest på grund af en flirt.",
        "Jeg har aldrig lavet en pinlig scorereplik.",
        "Jeg har aldrig fået en pinlig scorereplik.",
        "Jeg har aldrig prøvet at imponere nogen og gjort det stik modsatte.",
        "Jeg har aldrig fået et kompliment, som jeg ikke troede på.",
        "Jeg har aldrig været tiltrukket af en person, bare fordi de var sjove.",
        "Jeg har aldrig været på en date, hvor kemien var helt forkert.",
        "Jeg har aldrig været den første til at sige undskyld efter et skænderi.",
        "Jeg har aldrig været forelsket i en person, jeg mødte gennem venner.",
        "Jeg har aldrig kysset mere end én person på samme aften.",
        "Jeg har aldrig haft et hemmeligt hookup.",
        "Jeg har aldrig været sammen med en person, jeg mødte samme aften.",
        "Jeg har aldrig haft et booty call/eller været et",
        "Jeg har aldrig sendt en fræk besked midt om natten.",
        "Jeg har aldrig modtaget en fræk besked fra den forkerte person.",
        "Jeg har aldrig haft et crush på en person, der var meget ældre end mig.",
        "Jeg har aldrig haft et crush på en person, der var meget yngre end mig.",
        "Jeg har aldrig været sammen med en person, selvom jeg vidste, det ville skabe drama.",
        "Jeg har aldrig kysset en person, mens en anden var interesseret i mig.",
        "Jeg har aldrig været den anden person i en flirt.",
        "Jeg har aldrig haft et hemmeligt forhold.",
        "Jeg har aldrig flirtet med en eks, mens jeg datede en anden.",
        "Jeg har aldrig kysset en person, jeg lige havde mødt på en bytur.",
        "Jeg har aldrig været forelsket i en flirt.",
        "Jeg har aldrig haft en ferieflirt, der udviklede sig.",
        "Jeg har aldrig kysset en kollega til en firmafest.",
        "Jeg har aldrig været på date med to personer på samme tid.",
        "Jeg har aldrig været sammen med en person, hvis navn jeg næsten havde glemt.",
        "Jeg har aldrig haft et crush på en venindes eller vens søskende.",
        "Jeg har aldrig været tiltrukket af en person, jeg egentlig ikke burde være tiltrukket af.",
        "Jeg har aldrig kysset nogen for at gøre en anden jaloux.",
        "Jeg har aldrig været sammen med en person, fordi kemien bare var der.",
        "Jeg har aldrig haft en flirt, der blev opdaget af andre.",
        "Jeg har aldrig været nervøs for, at nogen fandt ud af, hvem jeg så.",
        "Jeg har aldrig haft en flirt med en nabo.",
        "Jeg har aldrig haft en flirt med en underviser eller træner.",
        "Jeg har aldrig været på en date, der endte meget anderledes end forventet.",
        "Jeg har aldrig flirtet med nogen, selvom jeg vidste, det ikke ville føre til noget.",
        "Jeg har aldrig været sammen med en person, jeg først ikke var interesseret i.",
        "Jeg har aldrig haft et crush på en person, jeg kun kendte online.",
        "Jeg har aldrig kysset nogen under et spil.",
        "Jeg har aldrig sendt et billede, jeg senere fortrød.",
        "Jeg har aldrig været sammen med en person, fordi mine venner opfordrede mig til det.",
        "Jeg har aldrig været forelsket i en person, jeg kun havde kendt i få dage.",
        "Jeg har aldrig haft en flirt, som ingen af mine venner kendte til.",
        "Jeg har aldrig været den, der tog det første skridt.",
        "Jeg har aldrig været for genert til at tage det første skridt.",
        "Jeg har aldrig haft en flirt, der kun varede én nat.",
        "Jeg har aldrig haft sommerfugle i maven over en person, jeg lige havde mødt.",
        "Jeg har aldrig kysset nogen på dansegulvet.",
        "Jeg har aldrig haft en flirt, der startede i byen.",
        "Jeg har aldrig været til en fest, hvor jeg endte med at kysse nogen.",
        "Jeg har aldrig haft et crush på en bartender.",
        "Jeg har aldrig haft et crush på en dørmand.",
        "Jeg har aldrig været sammen med en person, jeg mødte på ferie.",
        "Jeg har aldrig haft en flirt, der blev til et forhold.",
        "Jeg har aldrig været den første til at sige 'jeg kan godt lide dig'.",
        "Jeg har aldrig haft en flirt, som mine venner advarede mig imod.",
        "Jeg har aldrig været forelsket ved første blik.",
        "Jeg har aldrig haft en affære.",
        "Jeg har aldrig været den anden person i et utroskabsforhold.",
        "Jeg har aldrig været nogen utro.",
        "Jeg har aldrig kysset en person, der havde en kæreste.",
        "Jeg har aldrig været tiltrukket af min partners ven.",
        "Jeg har aldrig haft følelser for to personer på samme tid.",
        "Jeg har aldrig været på date med to personer på samme tid.",
        "Jeg har aldrig været sammen med en person samme dag, som jeg slog op med en anden.",
        "Jeg har aldrig været sammen med en eks' ven eller veninde.",
        "Jeg har aldrig været sammen med en vens eks.",
        "Jeg har aldrig kysset en person, jeg egentlig ikke burde have kysset.",
        "Jeg har aldrig været på en sexvideochat.",
        "Jeg har aldrig sendt et frækt billede, jeg senere fortrød.",
        "Jeg har aldrig modtaget et frækt billede, som overraskede mig.",
        "Jeg har aldrig haft en hemmelig flirt, mens jeg var i et forhold.",
        "Jeg har aldrig flirtet med en person foran min partner.",
        "Jeg har aldrig haft en flirt med en chef.",
        "Jeg har aldrig haft en flirt med en kunde.",
        "Jeg har aldrig haft en flirt med en underviser.",
        "Jeg har aldrig haft en flirt med en roomie.",
        "Jeg har aldrig været på date kun på grund af personens udseende.",
        "Jeg har aldrig været forelsket i en person, der var meget ældre end mig.",
        "Jeg har aldrig været forelsket i en person, der var meget yngre end mig.",
        "Jeg har aldrig været sammen med en person, jeg mødte på ferie.",
        "Jeg har aldrig haft en ferieflirt, der fortsatte efter ferien.",
        "Jeg har aldrig kysset nogen på en festival.",
        "Jeg har aldrig kysset nogen i en natklub.",
        "Jeg har aldrig kysset en total fremmed.",
        "Jeg har aldrig været på en date, der endte helt anderledes end planlagt.",
        "Jeg har aldrig taget hjem med en person, jeg mødte samme aften.",
        "Jeg har aldrig været nervøs for, at nogen opdagede min flirt.",
        "Jeg har aldrig fået følelser for et hookup.",
        "Jeg har aldrig haft et hookup, som blev til et forhold.",
        "Jeg har aldrig været forelsket i en person, jeg kun kendte online.",
        "Jeg har aldrig haft en flirt, der varede mindre end én dag.",
        "Jeg har aldrig kysset en person for at gøre en anden jaloux.",
        "Jeg har aldrig været sammen med en person, bare fordi kemien var der.",
        "Jeg har aldrig haft en flirt, som mine venner ikke måtte finde ud af.",
        "Jeg har aldrig været den, der ødelagde et forhold.",
        "Jeg har aldrig fået mit hjerte knust af et hookup.",
        "Jeg har aldrig været den, der knuste nogens hjerte.",
        "Jeg har aldrig fortrudt, hvem jeg tog hjem med.",
        "Jeg har aldrig haft en flirt, der blev virkelig kompliceret.",
        "Jeg har aldrig kysset en person, jeg først ikke kunne lide.",
        "Jeg har aldrig været tiltrukket af en person, jeg svor aldrig ville være min type.",
        "Jeg har aldrig haft et crush på en person, der var optaget.",
        "Jeg har aldrig overvejet at skrive til en eks, selvom jeg var i et forhold.",
        "Jeg har aldrig været jaloux på en eks' nye partner.",
        "Jeg har aldrig holdt en flirt skjult for mine venner.",
        "Jeg har aldrig håbet på, at en flirt ville udvikle sig til mere."


    ],
  },


  // SPIL: HEVM ER MEST TILBØJELIG TIL
  {
  id: "most_likely_to",
  title: "Hvem er mest tilbøjelig til?",
  headerTitle: "Hvem er\nMEST TILBØJELIG",

  mode: "normal",
  cardsPerRound: 10,

  description:
    "Et klassisk festspil hvor alle peger på den person, de mener passer bedst til udsagnet. Det handler om ærlighed, sjove historier og masser af grin.",

  rules: [
    "Én deltager læser kortet højt.",
    "Alle tæller ned fra 3 og peger samtidig på én person.",
    "Den person med flest stemmer tager 2 tår.",
    "Ved stemmelighed tager alle de udpegede 3 tår.",
  ],

  cards: [
    "Hvem er mest tilbøjelig til at blive smidt ud fra en bar for at være for fuld?",
    "Hvem er mest tilbøjelig til at sende en besked til deres eks, når de er stive?",
    "Hvem er mest tilbøjelig til at sige noget upassende på det værst tænkelige tidspunkt?",
    "Hvem er mest tilbøjelig til at falde i søvn under sex?",
    "Hvem er mest tilbøjelig til at tage hjem med en fremmed efter en bytur?",
    "Hvem er mest tilbøjelig til at skide i bukserne i offentligheden?",
    "Hvem er mest tilbøjelig til at have den mærkeligste pornohistorik?",
    "Hvem er mest tilbøjelig til at komme for sent til deres eget bryllup?",
    "Hvem er mest tilbøjelig til at tage en impulsiv tatovering?",
    "Hvem er mest tilbøjelig til at have haft en trekant?",
    "Hvem er mest tilbøjelig til at sende et nøgenbillede ved et uheld til den forkerte person?",
    "Hvem er mest tilbøjelig til at have haft sex på et upassende sted?",
    "Hvem er mest tilbøjelig til at lyve om antallet af sexpartnere?",
    "Hvem er mest tilbøjelig til at blive taget i at onanere?",
    "Hvem er mest tilbøjelig til at have sex i en bil?",
    "Hvem er mest tilbøjelig til at gå commando (uden undertøj) til en fest?",
    "Hvem er mest tilbøjelig til at have prøvet flest kinky ting i soveværelset?",
    "Hvem er mest tilbøjelig til at falde for en kollega?",
    "Hvem er mest tilbøjelig til at bruge håndjern eller blindfold under sex?",
    "Hvem er mest tilbøjelig til at blive forelsket i en, de lige har mødt?",
    "Hvem er mest tilbøjelig til at vågne op et sted, de ikke kan huske at være taget hen?",
    "Hvem er mest tilbøjelig til at kysse en fremmed på en bytur?",
    "Hvem er mest tilbøjelig til at blive forelsket efter én date?",
    "Hvem er mest tilbøjelig til at have et hemmeligt hookup?",
    "Hvem er mest tilbøjelig til at blive taget i at flirte med en bartender?",
    "Hvem er mest tilbøjelig til at få et sugemærke på det værst tænkelige sted?",
    "Hvem er mest tilbøjelig til at sende en fræk besked og straks fortryde det?",
    "Hvem er mest tilbøjelig til at ende i en sexvideochat?",
    "Hvem er mest tilbøjelig til at have haft et booty call?",
    "Hvem er mest tilbøjelig til at kysse to personer på samme aften?",
    "Hvem er mest tilbøjelig til at tage hjem med en person, de lige har mødt?",
    "Hvem er mest tilbøjelig til at være den første, der smider tøjet til en fest?",
    "Hvem er mest tilbøjelig til at få et crush på en underviser?",
    "Hvem er mest tilbøjelig til at blive forelsket i en kollega?",
    "Hvem er mest tilbøjelig til at have haft en ferieflirt?",
    "Hvem er mest tilbøjelig til at have flest one-night-stands?",
    "Hvem er mest tilbøjelig til at være medlem af en datingside i hemmelighed?",
    "Hvem er mest tilbøjelig til at blive opdaget i en pinlig situation?",
    "Hvem er mest tilbøjelig til at have haft sex på en festival?",
    "Hvem er mest tilbøjelig til at have haft sex på en første date?",
    "Hvem er mest tilbøjelig til at glemme navnet på en, de har været sammen med?",
    "Hvem er mest tilbøjelig til at have en hemmelig flirt, ingen kender til?",
    "Hvem er mest tilbøjelig til at sende et screenshot til den forkerte person?",
    "Hvem er mest tilbøjelig til at blive taget i at stalke en eks på sociale medier?",
    "Hvem er mest tilbøjelig til at have flest ekskærester?",
    "Hvem er mest tilbøjelig til at falde for den forkerte person?",
    "Hvem er mest tilbøjelig til at være sammen med en person, der allerede er optaget?",
    "Hvem er mest tilbøjelig til at blive taget i et kys?",
    "Hvem er mest tilbøjelig til at få følelser efter et hookup?",
    "Hvem er mest tilbøjelig til at være den, der skriver først efter en bytur?",
    "Hvem er mest tilbøjelig til at blive ghostet?",
    "Hvem er mest tilbøjelig til selv at ghoste nogen?",
    "Hvem er mest tilbøjelig til at få flest matches på Tinder?",
    "Hvem er mest tilbøjelig til at have haft en flirt med en chef?",
    "Hvem er mest tilbøjelig til at have haft en flirt med en kunde?",
    "Hvem er mest tilbøjelig til at have kysset en kollega til en julefrokost?",
    "Hvem er mest tilbøjelig til at være sammen med en eks igen?",
    "Hvem er mest tilbøjelig til at ende i et trekantsdrama?",
    "Hvem er mest tilbøjelig til at få et spontan kys i byen?",
    "Hvem er mest tilbøjelig til at sige 'jeg elsker dig' for tidligt?",
    "Hvem er mest tilbøjelig til at være utro?",
    "Hvem er mest tilbøjelig til at tilgive utroskab?",
    "Hvem er mest tilbøjelig til at have en sexvideo på telefonen?",
    "Hvem er mest tilbøjelig til at tage på en sexvideo-date?",
    "Hvem er mest tilbøjelig til at blive genkendt af en fra Tinder i byen?",
    "Hvem er mest tilbøjelig til at kysse en ven for sjov?",
    "Hvem er mest tilbøjelig til at være den vildeste i soveværelset?",
    "Hvem er mest tilbøjelig til at foreslå et spil 'Jeg har aldrig'?",
    "Hvem er mest tilbøjelig til at score på under 10 minutter?",
    "Hvem er mest tilbøjelig til at være den sidste, der går hjem fra byen?",
    "Hvem er mest tilbøjelig til at blive smidt ud af en natklub?",
    "Hvem er mest tilbøjelig til at vågne op uden at kunne huske aftenen?",
    "Hvem er mest tilbøjelig til at kysse en fremmed på en ferie?",
    "Hvem er mest tilbøjelig til at score på under en time?",
    "Hvem er mest tilbøjelig til at få et sugemærke dagen før en vigtig begivenhed?",
    "Hvem er mest tilbøjelig til at blive forelsket i en bartender?",
    "Hvem er mest tilbøjelig til at sende en fræk besked klokken 3 om natten?",
    "Hvem er mest tilbøjelig til at have et hemmeligt hookup?",
    "Hvem er mest tilbøjelig til at blive taget i at flirte?",
    "Hvem er mest tilbøjelig til at kysse en eks efter en bytur?",
    "Hvem er mest tilbøjelig til at have haft en sommerflirt?",
    "Hvem er mest tilbøjelig til at have været på flest datingsider?",
    "Hvem er mest tilbøjelig til at have haft en flirt med en kollega?",
    "Hvem er mest tilbøjelig til at ende i et trekantsdrama?",
    "Hvem er mest tilbøjelig til at falde for den forkerte person?",
    "Hvem er mest tilbøjelig til at have haft flest one-night-stands?",
    "Hvem er mest tilbøjelig til at sende et screenshot til den forkerte?",
    "Hvem er mest tilbøjelig til at have en hemmelig flirt, ingen kender til?",
    "Hvem er mest tilbøjelig til at kysse nogen under en leg?",
    "Hvem er mest tilbøjelig til at ende med at sove hos en fremmed?",
    "Hvem er mest tilbøjelig til at være den første på dansegulvet?",
    "Hvem er mest tilbøjelig til at danse på bordene?",
    "Hvem er mest tilbøjelig til at tabe sin telefon på en bytur?",
    "Hvem er mest tilbøjelig til at glemme deres jakke i byen?",
    "Hvem er mest tilbøjelig til at miste deres pung efter en fest?",
    "Hvem er mest tilbøjelig til at bestille alt for meget natmad?",
    "Hvem er mest tilbøjelig til at blive alt for fuld til en familiefest?",
    "Hvem er mest tilbøjelig til at falde i søvn på toilettet efter en bytur?",
    "Hvem er mest tilbøjelig til at vågne med tømmermænd og ingen erindring om aftenen?",
    "Hvem er mest tilbøjelig til at blive venner med fremmede i byen?",
    "Hvem er mest tilbøjelig til at ende i en sexvideochat?",
    "Hvem er mest tilbøjelig til at have sendt et billede, de senere fortrød?",
    "Hvem er mest tilbøjelig til at kysse to personer samme aften?",
    "Hvem er mest tilbøjelig til at score en person, der er meget ældre?",
    "Hvem er mest tilbøjelig til at score en person, der er meget yngre?",
    "Hvem er mest tilbøjelig til at være den første, der siger 'jeg elsker dig'?",
    "Hvem er mest tilbøjelig til at blive ghostet?",
    "Hvem er mest tilbøjelig til selv at ghoste nogen?",
    "Hvem er mest tilbøjelig til at skrive til en eks efter midnat?",
    "Hvem er mest tilbøjelig til at have flest ulæste beskeder fra flirts?",
    "Hvem er mest tilbøjelig til at være den, der ødelægger gruppens planer?",
    "Hvem er mest tilbøjelig til at få et crush på en underviser?",
    "Hvem er mest tilbøjelig til at blive forelsket på en ferie?",
    "Hvem er mest tilbøjelig til at blive fanget i en hvid løgn?",
    "Hvem er mest tilbøjelig til at komme til at afsløre en hemmelighed?",
    "Hvem er mest tilbøjelig til at blive taget i at stalke en eks?",
    "Hvem er mest tilbøjelig til at blive viralt af den forkerte grund?",
    "Hvem er mest tilbøjelig til at have den mest kaotiske kamerarulle?",
    "Hvem er mest tilbøjelig til at have den længste Snapchat-streak?",
    "Hvem er mest tilbøjelig til at have flest ubesvarede opkald efter en bytur?",
    "Hvem er mest tilbøjelig til at tage en spontan ferie med en person, de lige har mødt?",
    "Hvem er mest tilbøjelig til at blive gift først?",
    "Hvem er mest tilbøjelig til at blive skilt først?",
    "Hvem er mest tilbøjelig til at ende i Las Vegas og blive gift spontant?",
    "Hvem er mest tilbøjelig til at få en spontan piercing?",
    "Hvem er mest tilbøjelig til at købe en flybillet i fuldskab?",
    "Hvem er mest tilbøjelig til at tage et dumt væddemål alt for langt?",
    "Hvem er mest tilbøjelig til at miste alle deres ting på én aften?",
    "Hvem er mest tilbøjelig til at vågne op med en ny tatovering?",
    "Hvem er mest tilbøjelig til at blive smidt ud af et bryllup?",
    "Hvem er mest tilbøjelig til at starte et rygte ved et uheld?",
    "Hvem er mest tilbøjelig til at kysse den forkerte person?",
    "Hvem er mest tilbøjelig til at have haft en flirt med en nabo?",
    "Hvem er mest tilbøjelig til at blive taget i en løgn af deres partner?",
    "Hvem er mest tilbøjelig til at have den mest pinlige søgehistorik?",
    "Hvem er mest tilbøjelig til at få en sexvideo sendt til den forkerte?",
    "Hvem er mest tilbøjelig til at være den mest eventyrlystne i soveværelset?",
    "Hvem er mest tilbøjelig til at være den første til at foreslå et trekantsforhold?",
    "Hvem er mest tilbøjelig til at være den sidste, der forlader festen?",
    "Hvem er mest tilbøjelig til at score til en julefrokost?",
    "Hvem er mest tilbøjelig til at falde i søvn i en taxa?",
    "Hvem er mest tilbøjelig til at tage hjem uden deres sko?",
    "Hvem er mest tilbøjelig til at få et walk of shame?",
    "Hvem er mest tilbøjelig til at ende på en sexvideochat ved en fejl?",
    "Hvem er mest tilbøjelig til at blive kendt som gruppens største flirt?",
    "Hvem er mest tilbøjelig til at blive forelsket i en person, de lige har mødt?",
    "Hvem er mest tilbøjelig til at score en person, de lige har mødt?",
    "Hvem er mest tilbøjelig til at sende en fræk besked efter midnat?",
    "Hvem er mest tilbøjelig til at blive forelsket alt for hurtigt?",
    "Hvem er mest tilbøjelig til at have flest hemmelige beundrere?",
    "Hvem er mest tilbøjelig til at ende i et kærlighedsdrama?",
    "Hvem er mest tilbøjelig til at blive taget i at lyve om en flirt?",
    "Hvem er mest tilbøjelig til at falde for en person, de ikke kan få?",
    "Hvem er mest tilbøjelig til at skrive 'kommer du?' klokken 02 om natten?",
    "Hvem er mest tilbøjelig til at kysse nogen på første møde?",
    "Hvem er mest tilbøjelig til at have haft et hemmeligt forhold?",
    "Hvem er mest tilbøjelig til at have haft en flirt med en nabo?",
    "Hvem er mest tilbøjelig til at have kysset en venindes eller vens eks?",
    "Hvem er mest tilbøjelig til at få et crush på en chef?",
    "Hvem er mest tilbøjelig til at få et crush på en kunde?",
    "Hvem er mest tilbøjelig til at have flest uafsluttede flirts?",
    "Hvem er mest tilbøjelig til at have haft en flirt på en ferie?",
    "Hvem er mest tilbøjelig til at score til en festival?",
    "Hvem er mest tilbøjelig til at være den største flirt i gruppen?",
    "Hvem er mest tilbøjelig til at blive forelsket i den forkerte?",
    "Hvem er mest tilbøjelig til at få følelser efter én aften?",
    "Hvem er mest tilbøjelig til at have en hemmelig crush lige nu?",
    "Hvem er mest tilbøjelig til at blive opdaget i en akavet situation?",
    "Hvem er mest tilbøjelig til at blive afsløret af deres telefon?",
    "Hvem er mest tilbøjelig til at sende en besked, de straks fortryder?",
    "Hvem er mest tilbøjelig til at blive taget i at stalke nogen på Instagram?",
    "Hvem er mest tilbøjelig til at have den mest pinlige kamerarulle?",
    "Hvem er mest tilbøjelig til at have den mest pinlige søgehistorik?",
    "Hvem er mest tilbøjelig til at blive genkendt fra en datingside?",
    "Hvem er mest tilbøjelig til at blive afhængig af datingapps?",
    "Hvem er mest tilbøjelig til at have flest matches?",
    "Hvem er mest tilbøjelig til at tage det første skridt?",
    "Hvem er mest tilbøjelig til at kysse nogen i et kosteskab?",
    "Hvem er mest tilbøjelig til at blive taget på fersk gerning?",
    "Hvem er mest tilbøjelig til at blive afsløret af en ven?",
    "Hvem er mest tilbøjelig til at holde en flirt hemmelig længst?",
    "Hvem er mest tilbøjelig til at blive fanget i en hvid løgn?",
    "Hvem er mest tilbøjelig til at sige det forkerte under en date?",
    "Hvem er mest tilbøjelig til at blive droppet efter første date?",
    "Hvem er mest tilbøjelig til at blive ved med at gå tilbage til en eks?",
    "Hvem er mest tilbøjelig til at ende sammen med deres ungdomskærlighed?",
    "Hvem er mest tilbøjelig til at have haft et crush på en lærer?",
    "Hvem er mest tilbøjelig til at have haft et crush på en kendis?",
    "Hvem er mest tilbøjelig til at have haft et crush på en venindes eller vens søskende?",
    "Hvem er mest tilbøjelig til at score ved en julefrokost?",
    "Hvem er mest tilbøjelig til at kysse nogen under mistelten?",
    "Hvem er mest tilbøjelig til at blive jaloux hurtigst?",
    "Hvem er mest tilbøjelig til at overanalysere en besked?",
    "Hvem er mest tilbøjelig til at falde for en scorereplik?",
    "Hvem er mest tilbøjelig til selv at bruge en scorereplik?",
    "Hvem er mest tilbøjelig til at blive afsløret i en løgn om en flirt?",
    "Hvem er mest tilbøjelig til at få et 'walk of shame'?",
    "Hvem er mest tilbøjelig til at vågne op med en person, de lige har mødt?",
    "Hvem er mest tilbøjelig til at have kysset flest personer?",
    "Hvem er mest tilbøjelig til at have haft den vildeste ungdom?",
    "Hvem er mest tilbøjelig til at ende med at gifte sig med deres første store kærlighed?",
    "Hvem er mest tilbøjelig til at få en spontan tatovering på en ferie?",
    "Hvem er mest tilbøjelig til at tage den dårligste beslutning efter midnat?",
    "Hvem er mest tilbøjelig til at få overtalt de andre til en dum idé?",
    "Hvem er mest tilbøjelig til at være den sidste, der går i seng efter en fest?",
    "Hvem er mest tilbøjelig til at score uden overhovedet at prøve?",
    "Hvem er mest tilbøjelig til at være den mest eventyrlystne på en ferie?",
    "Hvem er mest tilbøjelig til at blive inviteret med til en efterfest?",
    "Hvem er mest tilbøjelig til at ende med at danse på en bardisk?",
    "Hvem er mest tilbøjelig til at miste kontrollen efter et par shots?",
    "Hvem er mest tilbøjelig til at glemme, hvad de lovede aftenen før?",
    "Hvem er mest tilbøjelig til at blive kendt på en bar efter én aften?",
    "Hvem er mest tilbøjelig til at blive venner med alle på en bytur?",
    "Hvem er mest tilbøjelig til at være den, der altid ender i centrum af dramaet?",
    "Hvem er mest tilbøjelig til at få flest telefonnumre på én aften?",
    "Hvem er mest tilbøjelig til at score den mest uventede person?",
    "Hvem er mest tilbøjelig til at blive den første, der foreslår en bytur?",
    "Hvem er mest tilbøjelig til at blive overtalt til næsten hvad som helst efter et par drinks?",
    "Hvem er mest tilbøjelig til at ende med den vildeste historie fra en ferie?",
    "Hvem er mest tilbøjelig til at have flest historier, de aldrig fortæller deres forældre?",
    "Hvem er mest tilbøjelig til at være den, alle tror har de vildeste historier?",
    "Hvem er mest tilbøjelig til at få et crush på en person, de lige har mødt?",
    "Hvem er mest tilbøjelig til at være sammen med en person, de mødte på en ferie?",
    "Hvem er mest tilbøjelig til at få et telefonnummer i byen?",
    "Hvem er mest tilbøjelig til at kysse en bartender?",
    "Hvem er mest tilbøjelig til at flirte sig til gratis drinks?",
    "Hvem er mest tilbøjelig til at glemme navnet på en person, de lige har kysset?",
    "Hvem er mest tilbøjelig til at falde for en scorereplik?",
    "Hvem er mest tilbøjelig til selv at bruge en virkelig dårlig scorereplik?",
    "Hvem er mest tilbøjelig til at ende på en spontan date?",
    "Hvem er mest tilbøjelig til at tage på weekendtur med en person, de næsten ikke kender?",
    "Hvem er mest tilbøjelig til at sende en besked, de håber bliver ignoreret dagen efter?",
    "Hvem er mest tilbøjelig til at have haft et hemmeligt crush i flere år?",
    "Hvem er mest tilbøjelig til at ende med at kysse den forkerte person?",
    "Hvem er mest tilbøjelig til at blive forelsket i en ven?",
    "Hvem er mest tilbøjelig til at have den mest dramatiske kærlighedshistorie?",
    "Hvem er mest tilbøjelig til at få følelser først?",
    "Hvem er mest tilbøjelig til at blive jaloux over ingenting?",
    "Hvem er mest tilbøjelig til at være den mest romantiske i gruppen?",
    "Hvem er mest tilbøjelig til at skrive en alt for lang besked til en flirt?",
    "Hvem er mest tilbøjelig til at have flest ubesvarede beskeder fra flirts?",
    "Hvem er mest tilbøjelig til at få en besked fra en eks midt om natten?",
    "Hvem er mest tilbøjelig til at have været på en katastrofal date?",
    "Hvem er mest tilbøjelig til at score den samme person to gange uden at opdage det?",
    "Hvem er mest tilbøjelig til at ende med at tage med til en efterfest?",
    "Hvem er mest tilbøjelig til at tage en udfordring alt for langt?",
    "Hvem er mest tilbøjelig til at miste hæmningerne først?",
    "Hvem er mest tilbøjelig til at blive overtalt til noget dumt?",
    "Hvem er mest tilbøjelig til at blive dagens største drama?",
    "Hvem er mest tilbøjelig til at få et impulskøb efter en bytur?",
    "Hvem er mest tilbøjelig til at blive venner med hele baren?",
    "Hvem er mest tilbøjelig til at få en spontan idé klokken 03 om natten?",
    "Hvem er mest tilbøjelig til at starte en fest hjemme hos sig selv efter byen?",
    "Hvem er mest tilbøjelig til at være den første, der foreslår shots?",
    "Hvem er mest tilbøjelig til at være den sidste, der stadig vil videre i byen?",
    "Hvem er mest tilbøjelig til at miste stemmen efter en bytur?",
    "Hvem er mest tilbøjelig til at være den første, der danser på dansegulvet?",
    "Hvem er mest tilbøjelig til at danse med en total fremmed?",
    "Hvem er mest tilbøjelig til at få en drink spildt ud over sig?",
    "Hvem er mest tilbøjelig til at falde på dansegulvet?",
    "Hvem er mest tilbøjelig til at få et kælenavn på en bytur?",
    "Hvem er mest tilbøjelig til at blive genkendt af en person fra en datingside?",
    "Hvem er mest tilbøjelig til at være den mest overbevisende flirt?",
    "Hvem er mest tilbøjelig til at score uden at prøve?",
    "Hvem er mest tilbøjelig til at blive afvist og prøve igen?",
    "Hvem er mest tilbøjelig til at komme til at kysse en, de ikke burde?",
    "Hvem er mest tilbøjelig til at blive forelsket i deres bedste ven?",
    "Hvem er mest tilbøjelig til at falde for en person, de lige har mødt på en festival?",
    "Hvem er mest tilbøjelig til at ende i en akavet trekantsituation?",
    "Hvem er mest tilbøjelig til at blive afsløret af deres kamerarulle?",
    "Hvem er mest tilbøjelig til at have den mest kaotiske lørdag aften?",
    "Hvem er mest tilbøjelig til at blive overtalt til at tage en spontan tatovering?",
    "Hvem er mest tilbøjelig til at tage en alt for ærlig sandhed eller konsekvens?",
    "Hvem er mest tilbøjelig til at kysse nogen som en udfordring?",
    "Hvem er mest tilbøjelig til at ende med at fortælle alt for meget om deres sexliv?",
    "Hvem er mest tilbøjelig til at være den første, der indrømmer en fræk hemmelighed?",
    "Hvem er mest tilbøjelig til at have den vildeste historie, ingen tror på?",
    "Hvem er mest tilbøjelig til at have været tæt på at blive taget på fersk gerning?",
    "Hvem er mest tilbøjelig til at få hele gruppen i problemer?",
    "Hvem er mest tilbøjelig til at blive husket af bartenderen fra sidste weekend?",
    "Hvem er mest tilbøjelig til at tage den mest risikable beslutning på en bytur?",
    "Hvem er mest tilbøjelig til at være den, der siger 'det bliver en rolig aften' og ender med at lukke byen?"
  ],
  },



  // SPIL : HVAD VIL DU HELST
  {
  id: "would_you_rather",
  title: "Hvad vil du helst?",
  headerTitle: "Hvad vil du\nHELST",

  cardsPerRound: "players",

  selectRandomPlayer: true,
  mode: "player_turns",

  description:
    "Hvad vil du helst er et spil, hvor én deltager ad gangen skal vælge mellem to svære, sjove eller akavede muligheder.",

  rules: [
    "Én deltager bliver udvalgt til at læse alle kortene højt i denne runde.",
    "{reader} læser kortet højt, og den udvalgte deltager vælger, hvad personen helst ville gøre.",
    "Alle der er enige i den udvalgte deltagers valg, tager én tår.",
    "Hver deltager får én tur til at vælge i løbet af runden.",
  ],

  cards: [
  {
    optionA: "Kunne tale alle sprog flydende",
    optionB: "kunne tale med dyr?",
  },
  {
    optionA: "Aldrig kunne bruge sociale medier igen",
    optionB: "aldrig kunne se fjernsyn igen?",
  },
  {
    optionA: "Have en million kroner nu",
    optionB: "få én krone, der fordobles hver dag i 30 dage?",
  },
  {
    optionA: "Have en perfekt hukommelse",
    optionB: "kunne glemme alle dine problemer?",
  },
  {
    optionA: "Kunne læse din partners tanker i sengen",
    optionB: "kunne få din partner til at gøre præcis, hvad du vil uden at sige noget?",
  },
  {
    optionA: "Være i et forhold, hvor sex altid er spontan og vild",
    optionB: "være i et forhold med planlagte, men meget intime og romantiske stunder?",
  },
  {
    optionA: "Prøve en ny sexstilling hver gang",
    optionB: "finde én, der virker, og bare bruge den?",
  },
  {
    optionA: "Have sex, hvor du altid er i kontrol",
    optionB: "lade din partner tage fuld kontrol?",
  },
  {
    optionA: "Kunne pause tiden, men kun i ét minut ad gangen",
    optionB: "kunne spole tiden tilbage, men kun 10 sekunder?",
  },
  {
    optionA: "Have menstruationssmerter",
    optionB: "have diarré hver dag i en måned?",
  },
  {
    optionA: "Drukne i tis",
    optionB: "drukne i lort?",
  },
  {
    optionA: "Have morgensex",
    optionB: "have sex om aftenen?",
  },
  {
    optionA: "Blive fuld af en enkelt tår alkohol",
    optionB: "aldrig blive fuld, uanset hvor meget du drikker?",
  },
  {
    optionA: "Altid have højlydt sex, uanset hvor du er",
    optionB: "aldrig kunne lave en lyd under sex?",
  },
  {
    optionA: "Have sex med en, der er virkelig dårlig til det, men superentusiastisk",
    optionB: "have sex med en, der er teknisk perfekt, men virker uengageret?",
  },
  {
    optionA: "Blive opdaget, mens du har sex et offentligt sted",
    optionB: "ved et uheld sende en fræk besked til din chef?",
  },
  {
    optionA: "Slikke en brugt toiletbørste",
    optionB: "tage en slurk af en tilfældig persons sved?",
  },
  {
    optionA: "Vågne op med en kæmpe bums midt på næsen hver dag",
    optionB: "altid have dårlig ånde, uanset hvor meget du børster tænder?",
  },
  {
    optionA: "Træde barfodet i en hundelort",
    optionB: "få en fugl til at skide direkte i din mund?",
  },
  {
    optionA: "Skide i bukserne i en elevator med mennesker",
    optionB: "kaste op ud over dit crush på en date?",
  },
  {
    optionA: "Aldrig kunne lyve igen",
    optionB: "altid blive afsløret, når du lyver?",
  },
  {
    optionA: "Kunne se 10 minutter ind i fremtiden",
    optionB: "rejse 100 år tilbage i tiden?",
  },
  {
    optionA: "Altid lugte af hvidløg",
    optionB: "altid lugte af våd hund?",
  },
  {
    optionA: "Altid være 30 minutter for tidligt",
    optionB: "altid være 30 minutter for sent?",
  },
  {
    optionA: "Få dine Google-søgninger sendt til hele din familie",
    optionB: "få alle dine private beskeder sendt til hele din familie?",
  },
  {
    optionA: "Glemme din partners fødselsdag hvert år",
    optionB: "glemme jeres årsdag hvert år?",
  },
  {
    optionA: "Have sex med lyset tændt resten af livet",
    optionB: "kun have sex i bælgmørke resten af livet?",
  },
  {
    optionA: "Aldrig kysse igen",
    optionB: "aldrig få et kram igen?",
  },
  {
    optionA: "Have sex én gang om året",
    optionB: "have sex hver dag resten af livet?",
  },
  {
    optionA: "Altid være den, der tager initiativet",
    optionB: "aldrig måtte tage initiativet?",
  },
  {
    optionA: "Blive taget i at have sex af dine forældre",
    optionB: "tage dine forældre i at have sex?",
  },
  {
    optionA: "Komme til at sige din eks' navn under sex",
    optionB: "komme til at sige din chefs navn under sex?",
  },
  {
    optionA: "Være nøgen foran alle dine kollegaer i ét minut",
    optionB: "sende et frækt billede til den forkerte person?",
  },
  {
    optionA: "Have en sexvideo lækket",
    optionB: "få læst alle dine beskeder højt foran din familie?",
  },
  {
    optionA: "Være den dårligste til at kysse",
    optionB: "være den dårligste i sengen?",
  },
  {
    optionA: "Gå commando resten af livet",
    optionB: "aldrig måtte gå i shorts igen?",
  },
  {
    optionA: "Kunne høre alles tanker på en date",
    optionB: "lade alle høre dine tanker?",
  },
  {
    optionA: "Blive ghostet af alle, du dater",
    optionB: "aldrig selv kunne ghoste nogen?",
  },
  {
    optionA: "Date en utrolig flot, men virkelig kedelig person",
    optionB: "date en gennemsnitlig, men vanvittigt sjov person?",
  },
  {
    optionA: "Falde i søvn under en date",
    optionB: "falde i søvn under sex?",
  },
  {
    optionA: "Have tømmermænd hver lørdag",
    optionB: "aldrig måtte drikke alkohol igen?",
  },
  {
    optionA: "Skide i bukserne én gang om året",
    optionB: "kaste op offentligt én gang om måneden?",
  },
  {
    optionA: "Have konstant dårlig ånde",
    optionB: "have konstant svedige hænder?",
  },
  {
    optionA: "Have én kæmpe bums midt i panden",
    optionB: "altid have fedtet hår?",
  },
  {
    optionA: "Gå én uge uden at gå i bad",
    optionB: "gå én uge uden at børste tænder?",
  },
  {
    optionA: "Slikke en andens armhule",
    optionB: "drikke et glas lunken pølsevand?",
  },
  {
    optionA: "Træde i hundelort hver dag i en måned",
    optionB: "altid have en sten i skoen?",
  },
  {
    optionA: "Have hikke resten af dagen",
    optionB: "nyse hvert femte minut?",
  },
  {
    optionA: "Være uden telefon i ét år",
    optionB: "være uden internet i ét år?",
  },
  {
    optionA: "Kunne flyve",
    optionB: "kunne teleportere?",
  },
  {
    optionA: "Kunne blive usynlig",
    optionB: "kunne læse tanker?",
  },
  {
    optionA: "Få din kamerarulle vist på storskærm",
    optionB: "få din browserhistorik vist på storskærm?",
  },
  {
    optionA: "Have evig kærlighed",
    optionB: "have ubegrænset rigdom?",
  },
  {
    optionA: "Være utrolig heldig",
    optionB: "være utrolig attraktiv?",
  },
  {
    optionA: "Være den sjoveste i rummet",
    optionB: "være den flotteste i rummet?",
  },
  {
  optionA: "Gå ind til dine forældre, mens de har sex",
  optionB: "de går ind til dig?",
  },
  {
    optionA: "Kysse din eks",
    optionB: "kysse din bedste vens eks?",
  },
  {
    optionA: "Have sex én gang foran 100 mennesker",
    optionB: "aldrig have sex igen?",
  },
  {
    optionA: "Skide i bukserne på første date",
    optionB: "kaste op ud over dit crush på første date?",
  },
  {
    optionA: "Være nøgen på arbejde i ét minut",
    optionB: "synge højt alene i et fyldt tog?",
  },
  {
    optionA: "Lade din partner vælge dit outfit resten af livet",
    optionB: "lade din partner vælge din frisure resten af livet?",
  },
  {
    optionA: "Drikke ét glas toiletvand",
    optionB: "spise én levende regnorm?",
  },
  {
    optionA: "Løbe nøgen gennem din gade",
    optionB: "sende din browserhistorik til hele din kontaktliste?",
  },
  {
    optionA: "Kysse den ældste person i rummet",
    optionB: "kysse den yngste voksne person i rummet?",
  },
  {
    optionA: "Blive taget i at lyve",
    optionB: "blive taget i at være utro?",
  },
  {
    optionA: "Lade din mor vælge din næste kæreste",
    optionB: "lade dine venner vælge din næste kæreste?",
  },
  {
    optionA: "Få din kamerarulle vist på storskærm",
    optionB: "få dine seneste 100 beskeder læst højt?",
  },
  {
    optionA: "Miste din telefon på en bytur",
    optionB: "miste din pung på en bytur?",
  },
  {
    optionA: "Have konstant tømmermænd i en måned",
    optionB: "aldrig måtte drikke alkohol igen?",
  },
  {
    optionA: "Sove med din eks én nat",
    optionB: "bo sammen med din eks i én måned?",
  },
  {
    optionA: "Komme til at sende en sexvideo-emoji til din chef",
    optionB: "kalde din chef 'skat' foran alle?",
  },
  {
    optionA: "Blive afvist foran alle dine venner",
    optionB: "afvise dit crush foran alle?",
  },
  {
    optionA: "Date en person, dine venner hader",
    optionB: "date en person, din familie hader?",
  },
  {
    optionA: "Have én kæmpe bums midt i ansigtet på dit bryllup",
    optionB: "snuble på vej op ad kirkegulvet?",
  },
  {
    optionA: "Vågne op med en tatovering, du ikke selv har valgt",
    optionB: "vågne op skaldet?",
  },
  {
    optionA: "Få en sexvideo-optagelse vist for dine venner",
    optionB: "lade dine forældre læse alle dine beskeder?",
  },
  {
    optionA: "Skulle fortælle din mest pinlige hemmelighed til din familie",
    optionB: "fortælle den til hele din arbejdsplads?",
  },
  {
    optionA: "Kaste op i en Uber",
    optionB: "skide i bukserne i en elevator?",
  },
  {
    optionA: "Få din værste eks tilbage",
    optionB: "aldrig finde en kæreste igen?",
  },
  {
    optionA: "Være strandet på en ø med din eks",
    optionB: "være strandet med din svigermor?",
  },
  {
    optionA: "Miste alle dine penge",
    optionB: "miste alle dine billeder?",
  },
  {
    optionA: "Kun spise kold pizza resten af livet",
    optionB: "aldrig spise pizza igen?",
  },
  {
    optionA: "Have diarré på en flyrejse",
    optionB: "have diarré på første date?",
  },
  {
    optionA: "Være uden toiletpapir resten af livet",
    optionB: "aldrig måtte låse toiletdøren?",
  },
  {
    optionA: "Få dit navn ændret af dine venner",
    optionB: "få din frisure valgt af dine venner resten af livet?",
  },
  {
    optionA: "Lugte af sved hele tiden",
    optionB: "have dårlig ånde hele tiden?",
  },
  {
    optionA: "Altid snorke højt",
    optionB: "altid prutte, når du griner?",
  },
  {
    optionA: "Falde i poolen til et bryllup",
    optionB: "vælte bryllupskagen?",
  },
  {
    optionA: "Gå én uge uden at bade",
    optionB: "gå én uge uden at børste tænder?",
  },
  {
    optionA: "Være låst inde på et offentligt toilet i tre timer",
    optionB: "sidde fast i en elevator med din eks i tre timer?",
  },
  {
    optionA: "Lade gruppen vælge din næste tatovering",
    optionB: "lade gruppen vælge dit næste hårklip?",
  },
  {
    optionA: "Spise en rå løg som et æble",
    optionB: "drikke et glas lunken tunvand?",
  },
  {
    optionA: "Blive stoppet af politiet hver uge",
    optionB: "aldrig kunne lyve igen?",
  },
  {
    optionA: "Altid have sand i sengen",
    optionB: "altid have en sten i skoen?",
  },
  {
    optionA: "Være 100 % ærlig resten af livet",
    optionB: "aldrig kunne sige din rigtige mening igen?",
  },
  {
    optionA: "Have evige tømmermænd",
    optionB: "aldrig kunne blive fuld igen?",
  },
  {
    optionA: "Date din værste eks igen",
    optionB: "være single resten af livet?",
  },
  {
    optionA: "Lade din mor vælge din næste kæreste",
    optionB: "lade dine venner vælge din næste kæreste?",
  },
  {
    optionA: "Få din browserhistorik vist på storskærm",
    optionB: "få din kamerarulle vist på storskærm?",
  },
  {
    optionA: "Få læst dine seneste 100 beskeder højt",
    optionB: "få vist alle dine billeder fra det sidste år?",
  },
  {
    optionA: "Blive ghostet af dit livs kærlighed",
    optionB: "ghoste dit livs kærlighed?",
  },
  {
    optionA: "Kysse den person, gruppen vælger",
    optionB: "lade gruppen læse dine seneste 20 beskeder?",
  },
  {
    optionA: "Blive afsløret i en løgn foran alle dine venner",
    optionB: "blive afsløret i en løgn foran din familie?",
  },
  {
    optionA: "Kaste op i en taxa",
    optionB: "kaste op i en Uber?",
  },
  {
    optionA: "Skide i bukserne på arbejdet",
    optionB: "skide i bukserne på en første date?",
  },
  {
    optionA: "Snuble på vej op til alteret",
    optionB: "glemme din partners navn under vielsen?",
  },
  {
    optionA: "Vågne op med en tatovering, du ikke selv har valgt",
    optionB: "vågne op uden øjenbryn?",
  },
  {
    optionA: "Få et kæmpe sugemærke dagen før en jobsamtale",
    optionB: "have læbestift i hele ansigtet uden at vide det?",
  },
  {
    optionA: "Komme til at like et opslag fra 2017",
    optionB: "komme til at sende en besked til den forkerte person?",
  },
  {
    optionA: "Sove ved siden af din eks en uge",
    optionB: "bo sammen med din eks en måned?",
  },
  {
    optionA: "Møde alle dine ekskærester til én middag",
    optionB: "møde alle dem, der har afvist dig, til én middag?",
  },
  {
    optionA: "Have konstant dårlig ånde",
    optionB: "altid lugte af sved?",
  },
  {
    optionA: "Prutte højlydt til et bryllup",
    optionB: "bøvse midt under en tale?",
  },
  {
    optionA: "Være uden deodorant en hel sommer",
    optionB: "være uden shampoo en hel sommer?",
  },
  {
    optionA: "Altid have toiletpapir siddende under skoen",
    optionB: "altid have spinat mellem tænderne?",
  },
  {
    optionA: "Være strandet med din værste eks",
    optionB: "være strandet med din svigermor?",
  },
  {
    optionA: "Lade din bedste ven styre din Tinder i en måned",
    optionB: "lade din mor styre din Tinder i en uge?",
  },
  {
    optionA: "Have én kæmpe bums på næsen til dit bryllup",
    optionB: "have dårlig ånde til dit bryllup?",
  },
  {
    optionA: "Være uden telefon i et år",
    optionB: "være uden internet i et år?",
  },
  {
    optionA: "Få 100.000 kr. mod at din familie ser din browserhistorik",
    optionB: "takke nej til pengene?",
  },
  {
    optionA: "Være den eneste ædru til en fest",
    optionB: "være den fuldeste til en familiefest?",
  },
  {
    optionA: "Blive låst inde på et offentligt toilet i fire timer",
    optionB: "sidde fast i en elevator med din eks i fire timer?",
  },
  {
    optionA: "Spise en hel citron med skræl",
    optionB: "drikke et glas lunken pølsevand?",
  },
  {
    optionA: "Have sand i sengen resten af livet",
    optionB: "have en sten i skoen resten af livet?",
  },
  {
    optionA: "Altid snorke",
    optionB: "altid tale i søvne?",
  },
  {
    optionA: "Lade gruppen vælge din næste frisure",
    optionB: "lade gruppen vælge din næste tatovering?",
  },
  {
    optionA: "Blive kendt for den mest pinlige sexvideo... nej vent",
    optionB: "..."
  },
  {
    optionA: "Falde i poolen til en fest",
    optionB: "rive bukserne i stykker på dansegulvet?",
  },
  {
    optionA: "Miste din pung på hver bytur",
    optionB: "miste din telefon på hver bytur?",
  },
  {
    optionA: "Kunne læse alles tanker",
    optionB: "lade alle læse dine tanker?",
  },
  {
    optionA: "Være sammen med én, der altid kommer en time for sent",
    optionB: "være sammen med én, der aldrig siger undskyld?",
  },
  {
    optionA: "Date én, der er utrolig flot, men virkelig kedelig",
    optionB: "date én, der er virkelig sjov, men slet ikke din type?",
  },
  {
    optionA: "Miste alle dine billeder",
    optionB: "miste alle dine kontakter?",
  },
  {
    optionA: "Være den, der altid starter drama",
    optionB: "være den, der altid skal rydde op efter drama?",
  },
  {
    optionA: "Altid have tømmermænd om lørdagen",
    optionB: "aldrig kunne drikke alkohol igen?",
  },
  {
    optionA: "Skulle fortælle din største hemmelighed til dine forældre",
    optionB: "fortælle den til din chef?",
  },
  {
    optionA: "Altid komme 30 minutter for sent",
    optionB: "altid komme 30 minutter for tidligt?",
  },
  {
    optionA: "Mødes med alle dine ekskærester én gang om måneden",
    optionB: "aldrig måtte tale med en eks igen?",
  },
  {
    optionA: "Kun spise kold pizza resten af livet",
    optionB: "aldrig spise pizza igen?",
  },
  {
    optionA: "Have en evig hikke",
    optionB: "nyse hvert femte minut resten af livet?",
  },
  {
    optionA: "Være helt ærlig resten af livet",
    optionB: "aldrig kunne sige, hvad du virkelig mener?",
  },
  {
    optionA: "Altid være den første på dansegulvet",
    optionB: "altid være den sidste, der går hjem fra festen?",
  },
  {
    optionA: "Få et kælenavn, du hader, resten af livet",
    optionB: "aldrig selv måtte vælge dit brugernavn igen?",
  },
  {
    optionA: "Vinde 10 millioner kroner, men aldrig kunne rejse",
    optionB: "rejse hele verden rundt, men altid være på et stramt budget?",
  },
  {
  optionA: "Have sex med lyset tændt resten af livet",
    optionB: "kun have sex i totalt mørke?",
  },
  {
    optionA: "Altid tage initiativet",
    optionB: "aldrig måtte tage initiativet?",
  },
  {
    optionA: "Kysse en fremmed",
    optionB: "kysse din eks?",
  },
  {
    optionA: "Have en sommerflirt hvert år",
    optionB: "kun være forelsket én gang i livet?",
  },
  {
    optionA: "Blive taget i at kysse en kollega",
    optionB: "blive taget i at kysse din eks?",
  },
  {
    optionA: "Kun date personer, der er meget ældre end dig",
    optionB: "kun date personer, der er meget yngre end dig?",
  },
  {
    optionA: "Være den, der altid bliver scoret",
    optionB: "være den, der altid skal score først?",
  },
  {
    optionA: "Have et kæmpe crush på din chef",
    optionB: "have et kæmpe crush på din bedste vens søskende?",
  },
  {
    optionA: "Komme til at sende en flirtende besked til din chef",
    optionB: "komme til at sende den til din eks?",
  },
  {
    optionA: "Blive kysset af den person, gruppen vælger",
    optionB: "lade gruppen vælge din næste date?",
  },
  {
    optionA: "Kun være sammen med én person resten af livet",
    optionB: "aldrig være i et forhold igen?",
  },
  {
    optionA: "Få et sugemærke dagen før en jobsamtale",
    optionB: "få et sugemærke dagen før et bryllup?",
  },
  {
    optionA: "Have en hemmelig flirt resten af året",
    optionB: "fortælle alle, hvem dit nuværende crush er?",
  },
  {
    optionA: "Kun date personer, dine venner hader",
    optionB: "kun date personer, din familie hader?",
  },
  {
    optionA: "Blive afvist af dit største crush",
    optionB: "afvise dit største crush ved en fejl?",
  },
  {
    optionA: "Kysse din bedste ven",
    optionB: "kysse din værste eks?",
  },
  {
    optionA: "Date én, der er vanvittigt god til at flirte",
    optionB: "date én, der aldrig flirter?",
  },
  {
    optionA: "Være den mest jaloux i forholdet",
    optionB: "være sammen med den mest jaloux person?",
  },
  {
    optionA: "Kun kysse på første date",
    optionB: "aldrig kysse på første date igen?",
  },
  {
    optionA: "Blive forelsket efter én date",
    optionB: "aldrig blive forelsket igen?",
  },
  {
    optionA: "Have et crush på en kollega",
    optionB: "have et crush på din bedste vens eks?",
  },
  {
    optionA: "Skulle fortælle dit største crush, hvad du føler",
    optionB: "aldrig måtte fortælle det?",
  },
  {
    optionA: "Kun date personer, du møder i byen",
    optionB: "kun date personer, du møder online?",
  },
  {
    optionA: "Blive ghostet efter hver første date",
    optionB: "selv skulle ghoste alle efter første date?",
  },
  {
    optionA: "Have kemi med alle, men aldrig møde den rigtige",
    optionB: "møde den rigtige med det samme, men aldrig opleve spændingen ved dating?",
  },
  {
    optionA: "Have den bedste date nogensinde, som aldrig fører til mere",
    optionB: "have en akavet første date, der ender med dit livs kærlighed?",
  },
  {
    optionA: "Skulle afsløre dit største celebrity-crush",
    optionB: "skulle afsløre dit største crush i vennekredsen?",
  },
  {
    optionA: "Lade din partner planlægge alle dates",
    optionB: "selv skulle planlægge alle dates?",
  },
  {
    optionA: "Have sommerfugle i maven hver gang I ses",
    optionB: "aldrig være nervøs på en date igen?",
  },
  {
    optionA: "Være utrolig god til at flirte",
    optionB: "være uimodståelig uden at vide hvorfor?",
  },
  ],
  },


  // SPIL: HVEM KENDER MIG BEDST
  {
  id: "know_me",
  title: "Kender du mig?",
  headerTitle: "Kender du\nMIG?",

  mode: "player_turns",
  cardsPerRound: "halfPlayers",
  screenType: "three_random_statements",

  description:
    "Kender du mig? er et spil, hvor én deltager vælger det udsagn, personen bedst kan relatere til — uden at sige det højt. De andre skal gætte, hvad deltageren har valgt.",

  rules: [
    "Én deltager bliver udvalgt pr. tur.",
    "Deltageren får 3 udsagn og vælger i hemmelighed det udsagn, personen bedst kan relatere til.",
    "De andre spillere skal i fællesskab gætte, hvilket udsagn deltageren valgte.",
    "Gætter gruppen korrekt, drikker den udvalgte deltager 2 tår.",
    "Gætter gruppen forkert, drikker alle andre 2 tår.",
    "Hvis der ikke er enighed, må uenige spillere gætte selv.",
    "Gætter en uenig spiller forkert, drikker personen 4 tår.",
    "Gætter en uenig spiller korrekt, må personen give 5 tår ud.",
  ],

  cards: [
    "Jeg har været tiltrukket af en kollega.",
    "Jeg har haft et crush på en chef.",
    "Jeg har været sammen med en person, der var betydeligt ældre end mig.",
    "Jeg har været sammen med en person, der var betydeligt yngre end mig.",
    "Jeg har fået følelser for en person, der allerede var optaget.",
    "Jeg har flirtet, selvom jeg godt vidste, jeg ikke burde.",
    "Jeg har fået stærkere følelser, end jeg havde regnet med.",
    "Jeg har haft en ferieflirt, der udviklede sig.",
    "Jeg har haft en flirt, der kun varede én dag.",
    "Jeg har været sammen med en person, hvis navn jeg næsten havde glemt dagen efter.",
    "Jeg har kysset en person for at gøre en anden jaloux.",
    "Jeg har været tiltrukket af en person, som mine venner advarede mig imod.",
    "Jeg har skrevet til en eks, selvom jeg vidste, det var en dårlig idé.",
    "Jeg har været forelsket i en person, jeg aldrig burde have fået følelser for.",
    "Jeg har holdt noget vigtigt skjult for en partner.",
    "Jeg har flirtet med en person for at få en andens opmærksomhed.",
    "Jeg har haft en flirt, som ingen nogensinde fandt ud af.",
    "Jeg har været tæt på at blive opdaget i en virkelig pinlig situation.",
    "Jeg har fortrudt, hvem jeg tog med hjem.",
    "Jeg har kysset en person, som først slet ikke var min type.",
    "Jeg har haft et crush på en venindes eller vens kæreste.",
    "Jeg har haft et crush på en venindes eller vens søskende.",
    "Jeg har flirtet med en person, som jeg aldrig troede ville være min type.",
    "Jeg har været forelsket i en person, jeg kun kendte online.",
    "Jeg har ødelagt en flirt ved at sige noget virkelig dumt.",
    "Jeg har været tiltrukket af en person, som var stik modsat min normale type.",
    "Jeg har haft en flirt, der blev meget mere seriøs, end jeg havde regnet med.",
    "Jeg har givet en person en chance, selvom jeg egentlig ikke var interesseret fra starten.",
    "Jeg har haft en flirt, der endte virkelig akavet.",
    "Jeg har taget det første kys.",
    "Jeg har kysset en person, bare fordi øjeblikket føltes rigtigt.",
    "Jeg har fået følelser hurtigere, end jeg havde lyst til at indrømme.",
    "Jeg har været den første til at skrive efter en bytur.",
    "Jeg har været på en date, der tog en meget uventet drejning.",
    "Jeg har haft en flirt med en person, jeg tilfældigt mødte igen.",
    "Jeg har været forelsket i en person, som mine venner ikke brød sig om.",
    "Jeg har været sammen med en person, selvom jeg vidste, det ville skabe drama.",
    "Jeg har taget en chance, selvom jeg godt vidste, den kunne ende galt.",
    "Jeg har haft en flirt, der startede som et væddemål.",
    "Jeg har været forelsket i en person, jeg næsten lige havde mødt.",
    "Jeg har været sammen med en person, bare fordi kemien var umulig at ignorere.",
    "Jeg har fået et crush på en kollega.",
    "Jeg har fået et crush på en person, der allerede var optaget.",
    "Jeg har kysset en person, jeg godt vidste, jeg ikke burde kysse.",
    "Jeg har flirtet mig til gratis drinks.",
    "Jeg har flirtet med en bartender.",
    "Jeg har haft en flirt, som ingen nogensinde fandt ud af.",
    "Jeg har været forelsket i en person, der ikke havde de samme følelser.",
    "Jeg har givet en eks en ny chance.",
    "Jeg har skrevet til en eks, mens jeg var fuld.",
    "Jeg har ghostet en person.",
    "Jeg har selv prøvet at blive ghostet.",
    "Jeg har stalket en eks på sociale medier.",
    "Jeg har været på en date, som jeg havde lyst til at flygte fra.",
    "Jeg har været på en blind date.",
    "Jeg har været sammen med en person, jeg mødte samme aften.",
    "Jeg har haft en sommerflirt.",
    "Jeg har haft en ferieflirt.",
    "Jeg har haft et booty call.",
    "Jeg har haft et forhold, som jeg holdt hemmeligt.",
    "Jeg har løjet om, hvor mange personer jeg har været sammen med.",
    "Jeg har fortrudt et kys dagen efter.",
    "Jeg har kysset mere end én person på samme aften.",
    "Jeg har haft et sugemærke, jeg måtte skjule.",
    "Jeg har været jaloux uden en god grund.",
    "Jeg har sagt 'jeg elsker dig', uden at mene det helt.",
    "Jeg har været forelsket ved første blik.",
    "Jeg har fået et crush på en underviser.",
    "Jeg har fået et crush på en ven.",
    "Jeg har kysset en ven.",
    "Jeg har haft en flirt med en kollega.",
    "Jeg har haft en flirt med en nabo.",
    "Jeg har haft en flirt med en bartender.",
    "Jeg har haft en flirt på en ferie.",
    "Jeg har taget det første skridt.",
    "Jeg har ventet med vilje på at svare en flirt.",
    "Jeg har overanalyseret en besked fra en flirt.",
    "Jeg har sovet hos en person, jeg mødte på en bytur.",
    "Jeg har været tæt på at blive opdaget i en pinlig situation.",
    "Jeg har gjort noget pinligt for at imponere en flirt.",
    "Jeg har haft en flirt, der endte helt galt.",
    "Jeg har været tiltrukket af en person, der var meget ældre end mig.",
    "Jeg har været tiltrukket af en person, der var meget yngre end mig.",
    "Jeg har haft svært ved at komme videre efter en eks.",
    "Jeg har været forelsket i den helt forkerte person.",
    "Jeg har haft en flirt med en person, mine venner ikke kunne lide.",
    "Jeg har haft en flirt, der udviklede sig til et forhold.",
    "Jeg har været sammen med en person alene på grund af kemien.",
    "Jeg har været sammen med en person, selvom jeg vidste, det var en dårlig idé.",
    "Jeg har kysset en person som en udfordring.",
    "Jeg har haft en flirt, der kun varede én aften.",
    "Jeg har været forelsket i en person, jeg næsten lige havde mødt.",
    "Jeg har flirtet, selvom jeg godt vidste, det ikke ville føre til noget.",
    "Jeg har skrevet først dagen efter en date.",
    "Jeg har været nervøs for at møde en flirts venner.",
    "Jeg har været nervøs for at møde en flirts familie.",
    "Jeg har holdt en flirt hemmelig for mine venner.",
    "Jeg har været den største flirt i vennegruppen.",
    "Jeg har været den første på dansegulvet på en bytur.",
    "Jeg har været den sidste til at forlade en fest.",
    "Jeg har mistet noget vigtigt på en bytur.",
    "Jeg har sendt en besked til den forkerte person.",
    "Jeg har lavet noget i fuldskab, som mine venner stadig minder mig om.",
    "Jeg har været den anden person i et forhold.",
    "Jeg har været en partner utro.",
    "Jeg har kysset en person, der allerede havde en kæreste.",
    "Jeg har haft et hemmeligt forhold.",
    "Jeg har haft følelser for to personer på samme tid.",
    "Jeg har datet to personer på samme tid.",
    "Jeg har været sammen med en person samme dag, som jeg slog op med en anden.",
    "Jeg har været sammen med en vens eks.",
    "Jeg har været tiltrukket af en kollega.",
    "Jeg har haft et crush på en chef.",
    "Jeg har været sammen med en person, der var meget ældre end mig.",
    "Jeg har været sammen med en person, der var meget yngre end mig.",
    "Jeg har fået følelser for en person, der allerede var optaget.",
    "Jeg har flirtet, selvom jeg godt vidste, jeg ikke burde.",
    "Jeg har fået stærkere følelser, end jeg havde regnet med.",
    "Jeg har haft en ferieflirt, der udviklede sig til mere.",
    "Jeg har haft en flirt, der kun varede én dag.",
    "Jeg har været sammen med en person, hvis navn jeg næsten havde glemt dagen efter.",
    "Jeg har kysset en person for at gøre en anden jaloux.",
    "Jeg har været tiltrukket af en person, som mine venner advarede mig imod.",
    "Jeg har skrevet til en eks, selvom jeg vidste, det var en dårlig idé.",
    "Jeg har været forelsket i en person, jeg aldrig burde have fået følelser for.",
    "Jeg har holdt noget vigtigt skjult for en partner.",
    "Jeg har flirtet med en person for at få en andens opmærksomhed.",
    "Jeg har haft en flirt, som ingen nogensinde fandt ud af.",
    "Jeg har været tæt på at blive opdaget i en virkelig pinlig situation.",
    "Jeg har fortrudt, hvem jeg tog med hjem.",
    "Jeg har kysset en person, som slet ikke var min type.",
    "Jeg har haft et crush på en venindes eller vens kæreste.",
    "Jeg har haft et crush på en venindes eller vens søskende.",
    "Jeg har flirtet med en person, som jeg aldrig troede ville være min type.",
    "Jeg har været forelsket i en person, jeg kun kendte online.",
    "Jeg har ødelagt en flirt ved at sige noget virkelig dumt.",
    "Jeg har været tiltrukket af en person, som var stik modsat min normale type.",
    "Jeg har haft en flirt, der blev meget mere seriøs, end jeg havde regnet med.",
    "Jeg har givet en person en chance, selvom kemien ikke var der fra starten.",
    "Jeg har haft en flirt, der endte virkelig akavet.",
    "Jeg har taget det første kys.",
    "Jeg har kysset en person, bare fordi øjeblikket føltes rigtigt.",
    "Jeg har fået følelser hurtigere, end jeg havde lyst til at indrømme.",
    "Jeg har været den første til at skrive efter en bytur.",
    "Jeg har været på en date, der tog en helt uventet drejning.",
    "Jeg har haft en flirt med en person, jeg tilfældigt mødte igen.",
    "Jeg har været forelsket i en person, som mine venner ikke kunne lide.",
    "Jeg har været sammen med en person, selvom jeg vidste, det ville skabe drama.",
    "Jeg har taget en chance, selvom jeg godt vidste, den kunne ende galt.",
    "Jeg har haft en flirt, der startede som et væddemål.",
    "Jeg har været forelsket i en person, jeg næsten lige havde mødt.",
    "Jeg har været sammen med en person, bare fordi kemien var umulig at ignorere.",
    "Jeg har været tiltrukket af en person, jeg godt vidste var en dårlig idé.",
    "Jeg har haft svært ved at sige nej til en flirt.",
    "Jeg har været den, der tog det første skridt.",
    "Jeg har kysset en person, jeg lige havde mødt.",
    "Jeg har været mere jaloux, end jeg havde lyst til at indrømme.",
    "Jeg har haft svært ved at komme videre efter en flirt.",
    "Jeg har givet en eks en ny chance.",
    "Jeg har holdt kontakten med en eks længere, end jeg burde.",
    "Jeg har flirtet med en person, bare fordi spændingen var der.",
    "Jeg har været tæt på at gøre noget, jeg sikkert ville have fortrudt.",
    "Jeg har haft en flirt, der aldrig burde være startet.",
    "Jeg har været forelsket i en person, der slet ikke passede til mig.",
    "Jeg har taget en chance i kærlighed, som overraskede mig selv.",
    "Jeg har været sammen med en person, selvom jeg vidste, det kun ville ende med drama.",
    "Jeg har haft en flirt, som jeg håbede ville forblive en hemmelighed.",
    "Jeg har været mere spontan, end mine venner tror.",
    "Jeg har haft en oplevelse, som mine venner aldrig ville gætte om mig.",
    "Jeg har været fristet af en person, jeg ikke burde være blevet fristet af.",
    "Jeg har gjort noget, bare fordi øjeblikket føltes rigtigt.",
    "Jeg har haft en aften, der udviklede sig langt vildere, end jeg havde regnet med.",
    "Jeg har fået følelser hurtigere, end jeg havde regnet med.",
    "Jeg har været forelsket i den forkerte.",
    "Jeg har været forelsket i en person, der allerede var optaget.",
    "Jeg har haft et crush på en kollega.",
    "Jeg har haft et crush på en chef.",
    "Jeg har haft et crush på en ven.",
    "Jeg har haft et crush på en venindes eller vens kæreste.",
    "Jeg har haft et crush på en venindes eller vens søskende.",
    "Jeg har skrevet til en eks, selvom jeg vidste, det var en dårlig idé.",
    "Jeg har givet en eks en ny chance.",
    "Jeg har haft svært ved at komme videre efter en eks.",
    "Jeg har været den første til at skrive efter en date.",
    "Jeg har været nervøs før et første kys.",
    "Jeg har været nervøs før en første date.",
    "Jeg har været på en blind date.",
    "Jeg har været på en date, der tog en helt uventet drejning.",
    "Jeg har været på en date, som jeg havde lyst til at flygte fra.",
    "Jeg har været forelsket i en person, mine venner ikke kunne lide.",
    "Jeg har været forelsket i en person, jeg næsten lige havde mødt.",
    "Jeg har været forelsket i en person, jeg kun kendte online.",
    "Jeg har haft en one-night-stand.",
    "Jeg har haft et booty call.",
    "Jeg har været sammen med en person, jeg mødte samme aften.",
    "Jeg har været sammen med en person, bare fordi kemien var umulig at ignorere.",
    "Jeg har været sammen med en person, selvom jeg vidste, det var en dårlig idé.",
    "Jeg har været sammen med en person, selvom jeg vidste, det ville skabe drama.",
    "Jeg har været sammen med en person, hvis navn jeg næsten havde glemt dagen efter.",
    "Jeg har haft sex på første date.",
    "Jeg har haft sex på en ferie.",
    "Jeg har haft sex i en bil.",
    "Jeg har haft sex på et badeværelse.",
    "Jeg har haft sex et sted, hvor jeg kunne være blevet opdaget.",
    "Jeg har haft sex, mens nogen andre var til stede.",
    "Jeg har kysset en person, jeg godt vidste, jeg ikke burde kysse.",
    "Jeg har kysset en fremmed.",
    "Jeg har kysset mere end én person på samme aften.",
    "Jeg har kysset en person som en udfordring.",
    "Jeg har kysset en person for at gøre en anden jaloux.",
    "Jeg har haft et sugemærke, jeg måtte skjule.",
    "Jeg har været den, der tog det første skridt.",
    "Jeg har sendt en besked til den forkerte person.",
    "Jeg har skrevet til en eks, mens jeg var fuld.",
    "Jeg har sendt en besked, jeg straks fortrød.",
    "Jeg har lavet noget pinligt i fuldskab, som mine venner stadig husker.",
    "Jeg har mistet noget vigtigt på en bytur.",
    "Jeg har sovet hos en person, jeg mødte på en bytur.",
    "Jeg har været den sidste til at forlade en fest.",
    "Jeg har været den første på dansegulvet.",
    "Jeg har flirtet mig til gratis drinks.",
    "Jeg har flirtet med en bartender.",
    "Jeg har fået et telefonnummer på en bytur.",
    "Jeg har taget hjem med en person efter en bytur.",
    "Jeg har vågnet op et sted, jeg ikke havde regnet med.",
    "Jeg har været tæt på at blive opdaget i en virkelig pinlig situation.",
    "Jeg har gjort noget dumt for at imponere en flirt.",
    "Jeg har holdt noget vigtigt skjult for en partner.",
    "Jeg har haft en flirt, som ingen nogensinde fandt ud af.",
    "Jeg har haft et forhold, som jeg holdt hemmeligt.",
    "Jeg har været den anden person i et forhold.",
    "Jeg har været en partner utro.",
    "Jeg har kysset en person, der allerede havde en kæreste.",
    "Jeg har haft følelser for to personer på samme tid.",
    "Jeg har datet to personer på samme tid.",
    "Jeg har løjet om, hvor mange personer jeg har været sammen med.",
    "Jeg har været jaloux uden en god grund.",
    "Jeg har sagt 'jeg elsker dig', uden at mene det helt.",
    "Jeg har flirtet, selvom jeg godt vidste, jeg ikke burde.",
    "Jeg har flirtet med en person for at få en andens opmærksomhed.",
    "Jeg har stalket en eks på sociale medier.",
    "Jeg har overanalyseret en besked fra en flirt.",
    "Jeg har været forelsket i den forkerte.",
    "Jeg har haft sex på første date.",
    "Jeg har skrevet til en eks, mens jeg var fuld.",
    "Jeg har flirtet mig til gratis drinks.",
    "Jeg har holdt et forhold hemmeligt.",
    "Jeg har fået et crush på en kollega.",
    "Jeg har haft lyst til at kysse en person, jeg lige havde mødt.",
    "Jeg har haft en flirt, som gik meget længere, end jeg havde planlagt.",
    "Jeg har været tæt på at skrive til en person, jeg ikke burde skrive til.",
    "Jeg har været sammen med en person, bare fordi spændingen var der.",
    "Jeg har været forelsket i en person, jeg kun kendte i få dage.",
    "Jeg har været tiltrukket af en person, bare fordi de virkede utilgængelige.",
    "Jeg har haft en flirt med en person, jeg mødte på sociale medier.",
    "Jeg har fået følelser for en person, der aldrig burde have fået dem.",
    "Jeg har været den, der tog initiativet til det første kys.",
    "Jeg har været sammen med en person, jeg aldrig havde troet ville være min type.",
    "Jeg har været mere jaloux, end jeg nogensinde indrømmede.",
    "Jeg har været fristet af en person, der allerede var optaget.",
    "Jeg har haft en flirt, der begyndte som en joke.",
    "Jeg har været sammen med en person, jeg vidste ville knuse mit hjerte.",
    "Jeg har kysset en person, bare fordi kemien var der.",
    "Jeg har været forelsket i en person, der aldrig fandt ud af det.",
    "Jeg har været den, der blev alt for hurtigt forelsket.",
    "Jeg har haft en flirt, som jeg stadig tænker tilbage på.",
    "Jeg har været tæt på at gøre noget, jeg sikkert ville have fortrudt.",
    "Jeg har haft lyst til at skrive til en eks, selvom jeg lod være.",
    "Jeg har været sammen med en person, som mine venner aldrig ville have godkendt.",
    "Jeg har været forelsket i en person, som var helt forkert for mig.",
    "Jeg har været den, der ikke kunne give slip.",
    "Jeg har haft en flirt, der endte med at blive meget mere kompliceret end forventet.",
    "Jeg har haft en oplevelse, som mine venner aldrig ville gætte om mig.",
    "Jeg har haft en flirt, som jeg stadig holder hemmelig.",
    "Jeg har været tiltrukket af en person, jeg egentlig ikke kunne lide.",
    "Jeg har haft en flirt med en person, jeg mødte gennem en ven.",
    "Jeg har været sammen med en person, bare fordi øjeblikket føltes rigtigt.",
    "Jeg har været forelsket i en person, der boede meget langt væk.",
    "Jeg har været den, der blev ved med at vende tilbage til den samme person.",
    "Jeg har haft svært ved at modstå en flirt.",
    "Jeg har været sammen med en person, selvom jeg vidste, det kun ville blive én gang.",
    "Jeg har haft en flirt, der startede med et væddemål.",
    "Jeg har været forelsket i en person, der ikke var god for mig.",
    "Jeg har haft en flirt, som jeg aldrig fortalte nogen om.",
    "Jeg har haft lyst til at tage en meget større chance, end jeg gjorde.",
    "Jeg har været den, der gjorde en flirt alt for kompliceret.",
    "Jeg har været den, der blev alt for investeret alt for hurtigt.",
    "Jeg har haft svært ved at skjule, hvem jeg var interesseret i.",
    "Jeg har været forelsket i en person, der var meget anderledes end mig.",
    "Jeg har været den, der sendte den første frække besked.",
    "Jeg har haft en flirt, som begyndte efter midnat.",
    "Jeg har været sammen med en person, fordi jeg ikke kunne modstå kemien.",
    "Jeg har haft en oplevelse, som stadig får mig til at rødme.",
    "Jeg har været tæt på at blive opdaget af de forkerte.",
    "Jeg har haft en flirt, der kun fungerede om natten.",
    "Jeg har været sammen med en person, jeg aldrig havde regnet med at ende sammen med.",
    "Jeg har haft en flirt, der sluttede lige så hurtigt, som den begyndte.",
    "Jeg har været mere spontan, end nogen ville tro.",
    "Jeg har haft sex med lyset tændt, selvom jeg helst ville lade være.",
    "Jeg har haft sex et sted, hvor nogen kunne være kommet ind.",
    "Jeg har været tæt på at blive opdaget under sex.",
    "Jeg har haft sex i et rum, hvor andre mennesker sov.",
    "Jeg har haft sex, mens andre var i samme bolig.",
    "Jeg har haft sex på et sted, hvor jeg aldrig troede, jeg ville gøre det.",
    "Jeg har været sammen med en person kun på grund af den fysiske kemi.",
    "Jeg har haft sex med en person, jeg næsten ikke kendte.",
    "Jeg har været sammen med en person igen, selvom jeg havde lovet mig selv, at jeg ikke ville.",
    "Jeg har haft sex med en person, jeg mødte samme dag.",
    "Jeg har været sammen med en person, som jeg stadig ikke burde have været sammen med.",
    "Jeg har haft sex med en person, som mine venner aldrig ville have gættet.",
    "Jeg har haft en oplevelse, jeg aldrig ville fortælle mine forældre om.",
    "Jeg har prøvet noget seksuelt, som overraskede mig selv.",
    "Jeg har haft en seksuel fantasi, jeg aldrig har fortalt nogen om.",
    "Jeg har været nysgerrig på noget seksuelt, jeg aldrig har prøvet.",
    "Jeg har haft lyst til at prøve noget, som de fleste ville synes var lidt grænseoverskridende.",
    "Jeg har været mere eventyrlysten, end folk tror.",
    "Jeg har overrasket mig selv med noget, jeg sagde ja til.",
    "Jeg har gjort noget, der stadig får mig til at smile, når jeg tænker tilbage på det.",
    "Jeg har haft lyst til at kysse en person, jeg lige havde mødt.",
    "Jeg har været tæt på at tage hjem med en fremmed.",
    "Jeg har flirtet med en person, bare for spændingens skyld.",
    "Jeg har haft en flirt, der aldrig burde være startet.",
    "Jeg har været sammen med en person, jeg aldrig troede, jeg ville ende med.",
    "Jeg har været forelsket i en person, der gav blandede signaler.",
    "Jeg har været den, der faldt først.",
    "Jeg har været den, der fik følelser først.",
    "Jeg har været den, der blev mest såret.",
    "Jeg har været den, der gjorde noget impulsivt for kærlighed.",
    "Jeg har kysset en person, bare fordi stemningen var der.",
    "Jeg har været tiltrukket af en person, jeg næsten intet vidste om.",
    "Jeg har haft en flirt, der udviklede sig meget hurtigere end forventet.",
    "Jeg har været tæt på at kysse en person, men sprang fra i sidste øjeblik.",
    "Jeg har haft en flirt med en person, jeg mødte tilfældigt.",
    "Jeg har været sammen med en person, som overraskede mig.",
    "Jeg har haft en flirt, jeg aldrig fik afsluttet ordentligt.",
    "Jeg har haft lyst til at skrive til en person midt om natten.",
    "Jeg har været forelsket i en person, jeg ikke burde tænke på.",
    "Jeg har været den, der blev hængende lidt for længe.",
    "Jeg har givet en person en chance nummer to.",
    "Jeg har haft en flirt, der sluttede uden nogen forklaring.",
    "Jeg har været den, der håbede på mere.",
    "Jeg har været sammen med en person, selvom mine venner sagde, jeg skulle lade være.",
    "Jeg har flirtet med en person, selvom jeg vidste, det ikke ville føre til noget.",
    "Jeg har været sammen med en person, jeg kun kendte i kort tid.",
    "Jeg har haft en flirt, der kun fungerede om natten.",
    "Jeg har været den, der blev overrasket over mine egne følelser.",
    "Jeg har haft en oplevelse, der stadig får mig til at smile.",
    "Jeg har været tæt på at tage en meget dum beslutning.",
    "Jeg har haft en flirt, som aldrig blev til noget.",
    "Jeg har været tiltrukket af en person, jeg aldrig troede ville være min type.",
    "Jeg har haft svært ved at lade en flirt gå.",
    "Jeg har haft en flirt, som endte med at blive et godt minde.",
    "Jeg har været sammen med en person, som mine venner aldrig ville have gættet.",
    "Jeg har haft en flirt, der blev alt for intens alt for hurtigt.",
    "Jeg har haft lyst til at tage en større chance, end jeg gjorde.",
    "Jeg har været den, der gjorde noget spontant, jeg aldrig havde planlagt.",
    "Jeg har været forelsket i en person, der kun var en del af mit liv i kort tid.",
    "Jeg har været den, der blev overrasket over, hvor hurtigt kemien opstod.",
    "Jeg har haft sex et sted, hvor jeg kunne være blevet opdaget.",
    "Jeg har haft sex et sted, hvor jeg bagefter tænkte 'hvad lavede jeg?'.",
    "Jeg har haft sex med en person, jeg næsten lige havde mødt.",
    "Jeg har haft sex med en person, som overraskede mig.",
    "Jeg har været tæt på at blive opdaget under sex.",
    "Jeg har haft sex et sted, jeg aldrig troede, jeg ville.",
    "Jeg har haft sex med en person, selvom jeg vidste, det var en dårlig idé.",
    "Jeg har været sammen med en person, kun fordi kemien var for god.",
    "Jeg har været mere eventyrlysten, end mine venner tror.",
    "Jeg har haft en seksuel oplevelse, der overraskede mig selv.",
    "Jeg har haft lyst til at prøve noget, jeg stadig ikke har prøvet.",
    "Jeg har været nysgerrig på noget, jeg aldrig har fortalt nogen om.",
    "Jeg har været tæt på at sige ja til noget meget grænseoverskridende.",
    "Jeg har haft en fantasi, som ville overraske mine venner.",
    "Jeg har været fristet af noget, jeg aldrig troede ville friste mig.",
    "Jeg har haft en oplevelse, som kun meget få mennesker kender til.",
    "Jeg har gjort noget, som stadig føles lidt uvirkeligt.",
    "Jeg har haft en oplevelse, der ændrede den måde, jeg ser mig selv på.",
    "Jeg har været sammen med en person, jeg aldrig havde forestillet mig.",
    "Jeg har haft en oplevelse, som jeg aldrig ville fortælle mine forældre om.",
    "Jeg har haft et booty call.",
    "Jeg har skrevet til en eks, mens jeg var fuld.",
    "Jeg har kysset en person, jeg ikke burde have kysset.",
    "Jeg har haft en ferieflirt.",
    "Jeg har haft sex på første date.",
    "Jeg har ghostet en person."
  ],
},



];

module.exports = { games };